{"name": "Отображение заказов пользователя", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=135.0.7049.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6289A5335+78597]\n\tGetHandleVerifier [0x00007FF6289A5390+78688]\n\t(No symbol) [0x00007FF6287591AA]\n\t(No symbol) [0x00007FF628760ABC]\n\t(No symbol) [0x00007FF628763B1C]\n\t(No symbol) [0x00007FF628763BEF]\n\t(No symbol) [0x00007FF6287A8D66]\n\t(No symbol) [0x00007FF6287D70EA]\n\t(No symbol) [0x00007FF6287A1AB6]\n\t(No symbol) [0x00007FF6287D7300]\n\t(No symbol) [0x00007FF6287FF2BB]\n\t(No symbol) [0x00007FF6287D6EC3]\n\t(No symbol) [0x00007FF6287A03F8]\n\t(No symbol) [0x00007FF6287A1163]\n\tGetHandleVerifier [0x00007FF628C4EEED+2870973]\n\tGetHandleVerifier [0x00007FF628C49698+2848360]\n\tGetHandleVerifier [0x00007FF628C66973+2967875]\n\tGetHandleVerifier [0x00007FF6289C017A+188746]\n\tGetHandleVerifier [0x00007FF6289C845F+222255]\n\tGetHandleVerifier [0x00007FF6289AD2B4+111236]\n\tGetHandleVerifier [0x00007FF6289AD462+111666]\n\tGetHandleVerifier [0x00007FF628993589+5465]\n\tBaseThreadInitThunk [0x00007FFCD8CFE8D7+23]\n\tRtlUserThreadStart [0x00007FFCDAAF14FC+44]", "trace": "self = <tests.test_order_feed_section.TestOrderFeedSection object at 0x000001FC773ABBB0>, login_user = None, create_order = None\nheader = <pages.header.Header object at 0x000001FC774C8FC0>, account_page = <pages.account_page.AccountPage object at 0x000001FC77432270>\norder_feed_page = <pages.orders_feed_page.OrdersFeedPage object at 0x000001FC774C8B00>\norders_history_page = <pages.orders_history_page.OrderHistoryPage object at 0x000001FC77432CF0>\n\n    @allure.title('Отображение заказов пользователя')\n    @allure.description(\n        'Проверка отображения заказов пользователя из раздела «История заказов» на странице «Лента заказов»')\n    def test_user_orders_display(self, login_user, create_order, header,\n                                 account_page, order_feed_page, orders_history_page):\n        header.click_account_button()\n        account_page.click_link_order_history()\n        user_orders = orders_history_page.get_order_numbers()\n        order_feed_page.open_order_feed_page()\n>       feed_orders = order_feed_page.get_orders_number()\n\ntests\\test_order_feed_section.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\orders_feed_page.py:29: in get_orders_number\n    orders_numbers = list(order_number.text for order_number in self.get_visible_elements(\npages\\orders_feed_page.py:29: in <genexpr>\n    orders_numbers = list(order_number.text for order_number in self.get_visible_elements(\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:90: in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py:395: in _execute\n    return self._parent.execute(command, params)\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:354: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x000001FC77590260>\nresponse = {'status': 404, 'value': '{\"value\":{\"error\":\"stale element reference\",\"message\":\"stale element reference: stale elemen...28993589+5465]\\\\n\\\\tBaseThreadInitThunk [0x00007FFCD8CFE8D7+23]\\\\n\\\\tRtlUserThreadStart [0x00007FFCDAAF14FC+44]\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\nE         (Session info: chrome=135.0.7049.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00007FF6289A5335+78597]\nE       \tGetHandleVerifier [0x00007FF6289A5390+78688]\nE       \t(No symbol) [0x00007FF6287591AA]\nE       \t(No symbol) [0x00007FF628760ABC]\nE       \t(No symbol) [0x00007FF628763B1C]\nE       \t(No symbol) [0x00007FF628763BEF]\nE       \t(No symbol) [0x00007FF6287A8D66]\nE       \t(No symbol) [0x00007FF6287D70EA]\nE       \t(No symbol) [0x00007FF6287A1AB6]\nE       \t(No symbol) [0x00007FF6287D7300]\nE       \t(No symbol) [0x00007FF6287FF2BB]\nE       \t(No symbol) [0x00007FF6287D6EC3]\nE       \t(No symbol) [0x00007FF6287A03F8]\nE       \t(No symbol) [0x00007FF6287A1163]\nE       \tGetHandleVerifier [0x00007FF628C4EEED+2870973]\nE       \tGetHandleVerifier [0x00007FF628C49698+2848360]\nE       \tGetHandleVerifier [0x00007FF628C66973+2967875]\nE       \tGetHandleVerifier [0x00007FF6289C017A+188746]\nE       \tGetHandleVerifier [0x00007FF6289C845F+222255]\nE       \tGetHandleVerifier [0x00007FF6289AD2B4+111236]\nE       \tGetHandleVerifier [0x00007FF6289AD462+111666]\nE       \tGetHandleVerifier [0x00007FF628993589+5465]\nE       \tBaseThreadInitThunk [0x00007FFCD8CFE8D7+23]\nE       \tRtlUserThreadStart [0x00007FFCDAAF14FC+44]\n\n.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py:229: StaleElementReferenceException"}, "description": "Проверка отображения заказов пользователя из раздела «История заказов» на странице «Лента заказов»", "steps": [{"name": "Кликаем на ссылку «Личный кабинет»", "status": "passed", "start": 1744563854764, "stop": 1744563855026}, {"name": "Нажимаем на ссылку \"История заказов\"", "status": "passed", "start": 1744563855026, "stop": 1744563855165}, {"name": "Получаем номера заказов пользователя из Истории заказов", "status": "passed", "start": 1744563855165, "stop": 1744563855716}, {"name": "Открываем страницу https://stellarburgers.nomoreparties.site/feed", "status": "passed", "start": 1744563855717, "stop": 1744563856358}, {"name": "Получаем список с номерами заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame\n  (Session info: chrome=135.0.7049.85); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception\nStacktrace:\n\tGetHandleVerifier [0x00007FF6289A5335+78597]\n\tGetHandleVerifier [0x00007FF6289A5390+78688]\n\t(No symbol) [0x00007FF6287591AA]\n\t(No symbol) [0x00007FF628760ABC]\n\t(No symbol) [0x00007FF628763B1C]\n\t(No symbol) [0x00007FF628763BEF]\n\t(No symbol) [0x00007FF6287A8D66]\n\t(No symbol) [0x00007FF6287D70EA]\n\t(No symbol) [0x00007FF6287A1AB6]\n\t(No symbol) [0x00007FF6287D7300]\n\t(No symbol) [0x00007FF6287FF2BB]\n\t(No symbol) [0x00007FF6287D6EC3]\n\t(No symbol) [0x00007FF6287A03F8]\n\t(No symbol) [0x00007FF6287A1163]\n\tGetHandleVerifier [0x00007FF628C4EEED+2870973]\n\tGetHandleVerifier [0x00007FF628C49698+2848360]\n\tGetHandleVerifier [0x00007FF628C66973+2967875]\n\tGetHandleVerifier [0x00007FF6289C017A+188746]\n\tGetHandleVerifier [0x00007FF6289C845F+222255]\n\tGetHandleVerifier [0x00007FF6289AD2B4+111236]\n\tGetHandleVerifier [0x00007FF6289AD462+111666]\n\tGetHandleVerifier [0x00007FF628993589+5465]\n\tBaseThreadInitThunk [0x00007FFCD8CFE8D7+23]\n\tRtlUserThreadStart [0x00007FFCDAAF14FC+44]\n\n", "trace": "  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\pages\\orders_feed_page.py\", line 29, in get_orders_number\n    orders_numbers = list(order_number.text for order_number in self.get_visible_elements(\n        OrdersFeedPageLocators.ORDERS_NUMBERS_LIST))\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\pages\\orders_feed_page.py\", line 29, in <genexpr>\n    orders_numbers = list(order_number.text for order_number in self.get_visible_elements(\n                          ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 90, in text\n    return self._execute(Command.GET_ELEMENT_TEXT)[\"value\"]\n           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 395, in _execute\n    return self._parent.execute(command, params)\n           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^\n  File \"C:\\Users\\admin\\PycharmProjects\\diplom_3\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744563856358, "stop": 1744563857129}], "parameters": [{"name": "web_driver", "value": "'chrome'"}], "start": 1744563854763, "stop": 1744563857132, "uuid": "484a30bc-b0ab-43b2-bbbe-d84812b91460", "historyId": "e0f7528471988e20bdcd6f387b67a746", "testCaseId": "b75d736bf0057ec64f62e4fc31eb37a6", "fullName": "tests.test_order_feed_section.TestOrderFeedSection#test_user_orders_display", "labels": [{"name": "suite", "value": "Лента заказов"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestOrderFeedSection"}, {"name": "host", "value": "DESKTOP-GVJUSQ6"}, {"name": "thread", "value": "7712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed_section"}]}